"""The ONLY supported build of the H1 recorder add-on (BMREC-04(b), BMREC-30, BMREC-31).

    python integrations/bookmap/build.py              # build + check + verify the jar reproduces the committed pin
    python integrations/bookmap/build.py --update-pin # build + check + write a new pin (commit it with the report)

Steps, each fatal on failure:
  1. The JDK is the pinned one (javac 21.0.12); compile classpath is ONLY Bookmap's own API jars (compile-only,
     never bundled).
  2. Compile; compute code_sha256 over every class except BuildInfo; bake it (and source_sha256) into BuildInfo;
     recompile; confirm code_sha256 is unchanged.
  3. Package with `jar` using a fixed timestamp (reproducible bytes).
  4. Run the must-fail fixture suite (BMREC-04(a)): every fixture must fail for its own reason, the clean jar
     must pass.
  5. Run the allowlist check on the FINAL jar (BMREC-01..03, -05, -31). Only a PASS reaches dist/.
  6. Write dist/check-report.txt (check output + fixture results + hashes). Without --update-pin the jar's
     SHA-256 must equal addon-pin.json, otherwise the jar is deleted: a jar whose hash is not in a pin record is
     not a loadable artefact (BMREC-04(c)).

No third-party Java library and no Maven/Gradle (BMREC-31). Python standard library only.
"""
import datetime as dt
import hashlib
import json
import os
import shutil
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, os.path.join(HERE, "tools"))
import allowlist_check as AC  # noqa: E402
import allowlist_fixtures as AF  # noqa: E402

JDK_HOME = os.environ.get("TDS_JDK_HOME", r"C:\Program Files\Microsoft\jdk-21.0.12.101-hotspot")
PINNED_JAVAC = "javac 21.0.12"
BOOKMAP_LIB = os.environ.get("TDS_BOOKMAP_LIB", r"C:\Program Files\Bookmap\lib")
COMPILE_JARS = ("bm-simplified-api-wrapper.jar", "bm-l1api.jar")
SRC = os.path.join(HERE, "src")
PKG_DIR = os.path.join("tds", "bookmap", "recorder")
DIST = os.path.join(HERE, "dist")
JAR_NAME = "tds-h1-recorder.jar"
PIN = os.path.join(HERE, "addon-pin.json")
ALLOWLIST = os.path.join(HERE, "allowlist.json")
ADDON_VERSION = "h1-1"
JAR_DATE = "2026-01-01T00:00:02Z"
BUILDINFO_CLASS = "tds/bookmap/recorder/BuildInfo.class"


def sha256_file(p):
    h = hashlib.sha256()
    with open(p, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def log(msg):
    print(msg, flush=True)


def run(cmd, **kw):
    log("$ " + " ".join(f'"{c}"' if " " in c else c for c in cmd))
    p = subprocess.run(cmd, capture_output=True, text=True, **kw)
    if p.stdout.strip():
        log(p.stdout.rstrip())
    if p.stderr.strip():
        log(p.stderr.rstrip())
    if p.returncode != 0:
        raise SystemExit(f"BUILD FAILED: command exited {p.returncode}")
    return p


def source_files():
    out = []
    for root, _dirs, files in os.walk(SRC):
        for f in files:
            if f.endswith(".java"):
                out.append(os.path.join(root, f))
    return sorted(out, key=lambda p: os.path.relpath(p, SRC).replace("\\", "/"))


def source_sha256(files):
    """Over relative path + LF-normalised bytes, so a CRLF checkout hashes the same as an LF one."""
    h = hashlib.sha256()
    for p in files:
        rel = os.path.relpath(p, SRC).replace("\\", "/")
        with open(p, "rb") as fh:
            data = fh.read().replace(b"\r\n", b"\n")
        h.update(rel.encode() + b"\0" + data + b"\0")
    return h.hexdigest()


def code_sha256(classes_dir):
    h = hashlib.sha256()
    names = []
    for root, _dirs, files in os.walk(classes_dir):
        for f in files:
            if f.endswith(".class"):
                names.append(os.path.relpath(os.path.join(root, f), classes_dir).replace("\\", "/"))
    for rel in sorted(names):
        if rel == BUILDINFO_CLASS:
            continue
        with open(os.path.join(classes_dir, rel), "rb") as fh:
            h.update(rel.encode() + b"\0" + fh.read() + b"\0")
    return h.hexdigest()


def write_buildinfo(gen_dir, code, source):
    d = os.path.join(gen_dir, PKG_DIR)
    os.makedirs(d, exist_ok=True)
    body = (
        "package tds.bookmap.recorder;\n\n"
        "/** GENERATED by integrations/bookmap/build.py -- do not edit, never committed. Methods (not constants)\n"
        " *  so no other class inlines these values and code_sha256 stays independent of them. */\n"
        "final class BuildInfo {\n"
        "    private BuildInfo() {\n    }\n\n"
        f"    static String addonVersion() {{\n        return \"{ADDON_VERSION}\";\n    }}\n\n"
        f"    static String codeSha256() {{\n        return \"{code}\";\n    }}\n\n"
        f"    static String sourceSha256() {{\n        return \"{source}\";\n    }}\n"
        "}\n")
    p = os.path.join(d, "BuildInfo.java")
    with open(p, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(body)
    return p


def compile_to(javac, cp, files, out):
    shutil.rmtree(out, ignore_errors=True)
    os.makedirs(out)
    run([javac, "--release", "21", "-encoding", "UTF-8", "-Xlint:all", "-Werror", "-cp", cp, "-d", out] + files)


def git_head():
    try:
        p = subprocess.run(["git", "-C", REPO, "rev-parse", "HEAD"], capture_output=True, text=True)
        return p.stdout.strip() if p.returncode == 0 else "UNKNOWN"
    except OSError:
        return "UNKNOWN"


def main(argv):
    update_pin = "--update-pin" in argv
    started = dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    log(f"== tds H1 recorder add-on build {started} (update_pin={update_pin})")
    javac = os.path.join(JDK_HOME, "bin", "javac.exe" if os.name == "nt" else "javac")
    jar_tool = os.path.join(JDK_HOME, "bin", "jar.exe" if os.name == "nt" else "jar")
    ver = run([javac, "-version"]).stdout.strip() or run([javac, "-version"]).stderr.strip()
    if not ver.startswith(PINNED_JAVAC):
        raise SystemExit(f"BUILD FAILED: JDK is {ver!r}, pinned {PINNED_JAVAC!r} (BMREC-31)")
    cp_jars = [os.path.join(BOOKMAP_LIB, j) for j in COMPILE_JARS]
    for j in cp_jars:
        if not os.path.isfile(j):
            raise SystemExit(f"BUILD FAILED: missing Bookmap API jar {j}")
    cp = os.pathsep.join(cp_jars)
    cp_record = [{"jar": os.path.basename(j), "sha256": sha256_file(j)} for j in cp_jars]
    log(f"compile classpath (compile-only, not bundled): {cp_record}")

    work = tempfile.mkdtemp(prefix="tds-h1-build-")
    try:
        files = source_files()
        src_sha = source_sha256(files)
        log(f"source files: {[os.path.relpath(f, SRC) for f in files]}")
        log(f"source_sha256 = {src_sha}")
        gen = os.path.join(work, "gen")
        c1, c2 = os.path.join(work, "classes1"), os.path.join(work, "classes")
        compile_to(javac, cp, files + [write_buildinfo(gen, "0" * 64, src_sha)], c1)
        code = code_sha256(c1)
        compile_to(javac, cp, files + [write_buildinfo(gen, code, src_sha)], c2)
        if code_sha256(c2) != code:
            raise SystemExit("BUILD FAILED: code_sha256 changed after baking BuildInfo (a class inlined it)")
        log(f"code_sha256 = {code}")

        manifest = os.path.join(work, "MANIFEST.MF")
        with open(manifest, "w", encoding="ascii", newline="\n") as fh:
            fh.write(f"Manifest-Version: 1.0\nImplementation-Title: tds-h1-recorder\n"
                     f"Implementation-Version: {ADDON_VERSION}\n")
        staging = os.path.join(work, JAR_NAME)
        run([jar_tool, "--create", "--file", staging, f"--date={JAR_DATE}", f"--manifest={manifest}",
             "-C", c2, "."])
        listing = run([jar_tool, "tf", staging]).stdout.split()
        log(f"jar tf: {listing}")

        allow = AC.load_allowlist(ALLOWLIST)
        log("-- must-fail fixture suite (BMREC-04a)")
        results = AF.run(javac, c2, cp_jars, work, allow, staging)
        bad = [r for r in results if not r["ok"]]
        for r in results:
            log(f"  [{'ok ' if r['ok'] else 'BAD'}] {r['name']:<34} expect {r['expect']}; got "
                f"{'PASS' if not r['violations'] else r['violations'][0][0] + ' x' + str(len(r['violations']))}")
        n_fail_fixtures = len(results) - 1
        log(f"fixtures: {n_fail_fixtures} must-fail, {sum(1 for r in results[1:] if r['ok'])} failed as expected; "
            f"clean passed: {results[0]['ok']}")
        if bad:
            for r in bad:
                log(f"  UNEXPECTED: {r['name']}: {r['violations']}")
            raise SystemExit("BUILD FAILED: the allowlist check did not behave as its fixtures require")

        log("-- allowlist check on the final jar (BMREC-01..03, -05, -31)")
        violations, facts = AC.check_jar(staging, allow)
        for rule, msg in violations:
            log(f"VIOLATION {rule}: {msg}")
        if violations:
            raise SystemExit("BUILD FAILED: allowlist check FAIL on the final jar")
        log(f"allowlist-check: RESULT PASS; getProvider_sites={facts['getprovider_sites']} "
            f"pipe_sites={facts['pipe_sites']}")

        jar_sha = sha256_file(staging)
        log(f"jar_sha256 = {jar_sha}")
        os.makedirs(DIST, exist_ok=True)
        dist_jar = os.path.join(DIST, JAR_NAME)
        if os.path.exists(dist_jar):
            os.chmod(dist_jar, 0o666)
            os.remove(dist_jar)
        shutil.copyfile(staging, dist_jar)
        check_record = {
            "result": "PASS",
            "checker_sha256": sha256_file(os.path.join(HERE, "tools", "allowlist_check.py")),
            "fixtures_sha256": sha256_file(os.path.join(HERE, "tools", "allowlist_fixtures.py")),
            "allowlist_sha256": sha256_file(ALLOWLIST),
            "must_fail_fixtures": n_fail_fixtures,
            "must_fail_failed_as_expected": sum(1 for r in results[1:] if r["ok"]),
            "clean_passed": results[0]["ok"],
            "getprovider_site": list(facts["getprovider_sites"][0][:2]),
            "pipe_site": list(facts["pipe_sites"][0][:2]),
        }
        report = os.path.join(DIST, "check-report.txt")
        with open(report, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(json.dumps({"jar_sha256": jar_sha, "code_sha256": code, "source_sha256": src_sha,
                                 "jdk": ver, "check": check_record, "built_at_utc": started,
                                 "fixtures": [{"name": r["name"], "ok": r["ok"],
                                               "first_violation": (r["violations"][0] if r["violations"] else None)}
                                              for r in results]}, indent=1))
        pin = {
            "_source": "BMREC-30 pin. Written only by integrations/bookmap/build.py --update-pin, committed with "
                       "the check result. The recorder recomputes the SHA-256 of the jar at its load location "
                       "and compares it with jar_sha256, and compares the hello's code/source SHA with this file.",
            "jar_file": JAR_NAME,
            "jar_sha256": jar_sha,
            "code_sha256": code,
            "source_sha256": src_sha,
            "addon_version": ADDON_VERSION,
            "jdk": ver,
            "compile_classpath": cp_record,
            "check": check_record,
            "built_at_utc": started,
            "built_from_commit": git_head(),
        }
        if update_pin:
            with open(PIN, "w", encoding="utf-8", newline="\n") as fh:
                json.dump(pin, fh, indent=2)
                fh.write("\n")
            # BMREC-30: "the pin changes only in a commit that also carries the check output"
            shutil.copyfile(report, os.path.join(HERE, "addon-check-report.json"))
            log(f"pin written: {os.path.relpath(PIN, REPO)} (+ addon-check-report.json)")
        else:
            try:
                with open(PIN, encoding="utf-8") as fh:
                    old = json.load(fh)
            except (OSError, ValueError):
                old = {}
            same = all(old.get(k) == pin[k] for k in ("jar_sha256", "code_sha256", "source_sha256"))
            if not same:
                os.remove(dist_jar)
                raise SystemExit("BUILD FAILED: the jar does not reproduce the committed pin "
                                 f"(pin jar {old.get('jar_sha256')}, built {jar_sha}); dist jar removed. "
                                 "If the source changed on purpose, rebuild with --update-pin and commit the pin.")
            log("pin reproduced: jar/code/source SHA-256 equal addon-pin.json")
        log(f"BUILD OK -> {os.path.relpath(dist_jar, REPO)}")
        return 0
    finally:
        shutil.rmtree(work, ignore_errors=True)


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
