#!/usr/bin/env python3
"""Regenerate every DERIVED copy of the session model from the single source
(docs/architecture/sessions.json). CLAUDE.md §21 asks for sessions that are configurable and historically
reproducible; before 2026-09-18 the windows were six hand-kept copies with no generator and no drift test, so
"configurable" meant "edit four files and hope". scripts/tests/test_sessions.py runs this in --check mode, so
drift fails the build.

    python3 scripts/sync-sessions.py --check    # exit 1 and name the drift
    python3 scripts/sync-sessions.py --write    # rewrite the derived spots

Derived spots (add new ones HERE, never a new hand-kept list):
  - schemas/trade-file.schema.json   session.enum                <- sessions + off_label
  - scripts/chart.js                 const SESSIONS = [...]      <- sessions (window table)
  - scripts/chart.js                 const KZ_WEIGHT = {...}     <- weights (class per asset class)

chart.js is generated in place rather than injected through build-artifact's params object -- unlike the i18n
catalog, which genuinely varies per page. The session table does not vary per page, and a build-time parameter
would mean a page rendered from a stale snapshot silently carried a stale session model with no way to notice.
Generating the literal keeps the drift visible to `--check` and to `git diff`.
"""
import argparse
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "scripts"))
from repo_paths import repo_rel
import sessions as S

TRADE_SCHEMA = os.path.join(ROOT, "docs", "architecture", "schemas", "trade-file.schema.json")
CHART = os.path.join(ROOT, "scripts", "chart.js")


def session_enum():
    return list(S.ORDER) + [S.OFF]


def session_description():
    return (f"Session/killzone of the entry, derived from the entry time in the EXCHANGE-LOCAL clock for that "
            f"date (DST-aware), not in UTC. GENERATED by scripts/sync-sessions.py from "
            f"docs/architecture/sessions.json (model v{S.VERSION}); do not hand-edit. The windows and the "
            f"reasoning behind them are docs/architecture/session-model.md. `{S.OFF}` means inside no window, "
            f"which includes every weekend timestamp for every instrument.")


def chart_lines():
    """The two generated chart.js literals, as source text."""
    sess = ",".join("{key:'%s',name:'%s',tz:'%s',a:%s,b:%s}"
                    % (w["key"], w["name"], w["tz"], f"{w['a']:g}", f"{w['b']:g}") for w in S.js_sessions())
    wts = ", ".join("%s:{%s}" % (cls, ",".join(f"{k}:'{v}'" for k, v in m.items()))
                    for cls, m in S.js_weights().items())
    return f"const SESSIONS = [{sess}];", "const KZ_WEIGHT = {%s};" % wts


def _replace_const(src, name, line):
    pat = re.compile(rf"^const {name} = .*$", re.M)
    if not pat.search(src):
        raise SystemExit(f"{CHART}: no `const {name} = ...` line to generate into. If it was renamed, update "
                         f"scripts/sync-sessions.py rather than hand-keeping the value.")
    return pat.sub(lambda _: line, src, count=1)


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--check", action="store_true")
    g.add_argument("--write", action="store_true")
    a = ap.parse_args()

    drift = []

    doc = json.load(open(TRADE_SCHEMA, encoding="utf-8"))
    field = doc["properties"]["session"]
    want_enum, want_desc = session_enum(), session_description()
    if field.get("enum") != want_enum:
        drift.append(f"{repo_rel(TRADE_SCHEMA, ROOT)} session.enum is {field.get('enum')}, "
                     f"registry says {want_enum}")
    if field.get("description") != want_desc:
        drift.append(f"{repo_rel(TRADE_SCHEMA, ROOT)} session.description does not match the registry")
    if a.write:
        field["enum"], field["description"] = want_enum, want_desc

    src = open(CHART, encoding="utf-8").read()
    sess_line, wt_line = chart_lines()
    for name, line in (("SESSIONS", sess_line), ("KZ_WEIGHT", wt_line)):
        cur = re.search(rf"^const {name} = .*$", src, re.M)
        if cur is None or cur.group(0) != line:
            drift.append(f"scripts/chart.js `const {name}` does not match docs/architecture/sessions.json")
        if a.write:
            src = _replace_const(src, name, line)

    if a.check:
        for d in drift:
            print(f"DRIFT: {d}")
        if drift:
            print("\nRun `python3 scripts/sync-sessions.py --write` after editing "
                  "docs/architecture/sessions.json.")
            return 1
        print("OK: every derived session copy matches docs/architecture/sessions.json")
        return 0

    if not drift:
        print("no drift; nothing to write")
        return 0
    with open(TRADE_SCHEMA, "w", encoding="utf-8") as fh:
        json.dump(doc, fh, indent=2, ensure_ascii=False)
        fh.write("\n")
    open(CHART, "w", encoding="utf-8").write(src)
    for d in drift:
        print(f"wrote: {d}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
