#!/usr/bin/env python3
"""Regenerate every DERIVED copy of the method registry from the single source
(docs/architecture/methods.json). JSON Schema cannot $ref an enum out of an arbitrary file in a way every
validator honours, so the dimension shape is generated here instead of hand-maintained -- and
scripts/tests/test_methods_sync.py runs this in --check mode so drift fails the build.

    python3 scripts/sync-methods.py --check    # exit 1 and name the drift
    python3 scripts/sync-methods.py --write    # rewrite the derived spots

Derived spots (add new ones HERE, never a new hand-kept list):
  - schemas/automation-config.schema.json  markets.<m>.dimensions.{properties,required}  <- dimensions[*].markets

Generating the shape from dimensions[*].markets is what keeps SYSTEM-DESIGN.md §12's property alive: a market
that has no source for a dimension does not get a flag it would silently ignore -- the key is simply absent and
additionalProperties:false turns a bad config into a validation error.
"""
import argparse, json, os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "scripts"))
import methods as M

SCHEMA = os.path.join(ROOT, "docs", "architecture", "schemas", "automation-config.schema.json")


def _desc(market):
    dims = M.dimensions(market)
    if market == "cfd":
        return ("Wyckoff + ICT only -- the 2-of-4 structural cap. GENERATED by scripts/sync-methods.py from "
                "docs/architecture/methods.json; do not hand-edit. Note that even these two are close to "
                "non-independent on the bridge's TICK volume (SYSTEM-DESIGN.md section 6.1): Wyckoff credit is "
                "reduced there, it is not scored at face value.")
    return (f"The {len(dims)} Confluence Score dimensions (SYSTEM-DESIGN.md section 6.2). GENERATED by "
            "scripts/sync-methods.py from docs/architecture/methods.json; do not hand-edit. Disabling one "
            "removes it from engaged_count -- it can only LOWER the number of dimensions available to a "
            "verdict, never raise a score. Below the mode minimum (SOLO 1, NORMAL 2, ENHANCED 3, STRICT 3) no "
            "live TRADE verdict can pass at all. SOLO (added 2026-09-12) only applies to a preset that itself "
            "names exactly one dimension -- never to a multi-dimension preset degraded at runtime -- and "
            "carries a higher threshold (85) than NORMAL's (70) since a single dimension has no "
            "cross-confirmation.")


def desired():
    """(market, block) for every derived dimensions block."""
    out = []
    for m in M.markets():
        dims = M.dimensions(m)
        out.append((m, {
            "type": "object",
            "additionalProperties": False,
            "required": list(dims),
            "description": _desc(m),
            "properties": {d: {"type": "boolean", "description": M.DIMENSIONS[d]["label"]} for d in dims},
        }))
    return out


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--check", action="store_true")
    g.add_argument("--write", action="store_true")
    a = ap.parse_args()

    doc = json.load(open(SCHEMA, encoding="utf-8"))
    drift = []
    for market, block in desired():
        cur = doc["properties"]["markets"]["properties"][market]["properties"].get("dimensions")
        if cur != block:
            drift.append(market)
            if a.write:
                doc["properties"]["markets"]["properties"][market]["properties"]["dimensions"] = block

    if a.check:
        for m in drift:
            print(f"DRIFT: {os.path.relpath(SCHEMA, ROOT)} markets.{m}.dimensions does not match "
                  f"docs/architecture/methods.json (expected {M.dimensions(m)})")
        return 1 if drift else 0

    if drift:
        with open(SCHEMA, "w", encoding="utf-8") as f:
            json.dump(doc, f, indent=2, ensure_ascii=False)
            f.write("\n")
        print(f"wrote {os.path.relpath(SCHEMA, ROOT)}: {', '.join(drift)}")
    else:
        print("no drift; nothing to write")
    return 0


if __name__ == "__main__":
    sys.exit(main())
